[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-routing"
  version = "2.1.4"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/lube/mutantes"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.1"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"